"""Central configuration for the RAFTS SIH26055 prototype."""

NUM_BANDS = 20
NUM_RECEIVERS = 2
NUM_SLOTS = 500

FREQ_MIN_MHZ = 500.0
FREQ_MAX_MHZ = 18000.0

PD = 0.90
PFA = 0.01
SENSITIVITY_DB = -120.0  # simulation parameter, not a calibrated hardware claim

RETUNE_DELAY_SLOTS = 1
MAX_AGE_SLOTS = 24

DTS_DISCOUNT = 0.985
DTS_PRIOR_ALPHA = 1.0
DTS_PRIOR_BETA = 1.0

TEMPORAL_MIN_HITS = 4
TEMPORAL_MIN_CONFIDENCE = 0.65
TEMPORAL_MAX_BONUS = 0.20
TEMPORAL_TOLERANCE_SLOTS = 2

TRANSITION_ENABLED = False
TRANSITION_MIN_SUPPORT = 5
TRANSITION_MIN_CONFIDENCE = 0.70
TRANSITION_MAX_BONUS = 0.10
TRANSITION_DISCOUNT = 0.98

RANDOM_SEED = 2026
